### ISSUE TITLE
Where's the Frostbite3Editor?

### ISSUE THREAD

**Issue by z3ntu** [GreyDynamics/BF1_TunguskaClosedAlphaPC_403930_EBX#1]
It's no longer available on your profile...
https://github.com/GreyDynamics/Frostbite3_Editor

**Comment by GreyDynamics** [comment]
Hello,
**Its back again and will get an update for BF1 soon!**

https://github.com/GreyDynamics/Frostbite3_Editor

**Comment by z3ntu** [comment]
What happened or did you take it offline intentionally?

**Comment by GreyDynamics** [comment]
In the past months i worked on Battlefield Editor, so i took it down.
The tool is for all Battlefield titles and is mostly memory and ebx hook based. Client and Server modification supported over network. (No release planned yet.)

So it was not sure if i will continue FB3Editor...
BF1 is Frostbite 3.x and editor has the mapmaking backend which is good.

Modification with FB3Editor will not be supported in the future anymore (readonly) but get still updated to work with Battlefield 3, Hardline, Battlefront and BF1 aswell, it will export only to Battlefield Editor then.

Sorry for my bad english :/
